In [210]:
# Nama   : Mia Amaliah 
# NIM    : 1202922002
# Tugas : Market Basket Analysis

import numpy as np 
import pandas as pd 
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/the-bread-basket/bread basket.csv

In [211]:
market = pd.read_csv('../input/the-bread-basket/bread basket.csv')
market.head(10)

   Transaction           Item         date_time period_day weekday_weekend
0            1          Bread  30-10-2016 09:58    morning         weekend
1            2   Scandinavian  30-10-2016 10:05    morning         weekend
2            2   Scandinavian  30-10-2016 10:05    morning         weekend
3            3  Hot chocolate  30-10-2016 10:07    morning         weekend
4            3            Jam  30-10-2016 10:07    morning         weekend
5            3        Cookies  30-10-2016 10:07    morning         weekend
6            4         Muffin  30-10-2016 10:08    morning         weekend
7            5         Coffee  30-10-2016 10:13    morning         weekend
8            5         Pastry  30-10-2016 10:13    morning         weekend
9            5          Bread  30-10-2016 10:13    morning         weekend

In [212]:
#cek jumlah data dan kolom

market.shape

(20507, 5)

In [213]:
#cek apakah ada data yang kosong

market.isna().sum()

Transaction        0
Item               0
date_time          0
period_day         0
weekday_weekend    0
dtype: int64

In [214]:
#cek type data

market.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20507 entries, 0 to 20506
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Transaction      20507 non-null  int64
 1   Item             20507 non-null  object
 2   date_time        20507 non-null  object
 3   period_day       20507 non-null  object
 4   weekday_weekend  20507 non-null  object
dtypes: int64(1), object(4)
memory usage: 801.2+ KB

In [215]:
market.Item.unique()

array(['Bread', 'Scandinavian', 'Hot chocolate', 'Jam', 'Cookies',
       'Muffin', 'Coffee', 'Pastry', 'Medialuna', 'Tea', 'Tartine',
       'Basket', 'Mineral water', 'Farm House', 'Fudge', 'Juice',
       "Ella's Kitchen Pouches", 'Victorian Sponge', 'Frittata',
       'Hearty & Seasonal', 'Soup', 'Pick and Mix Bowls', 'Smoothies',
       'Cake', 'Mighty Protein', 'Chicken sand', 'Coke',
       'My-5 Fruit Shoot', 'Focaccia', 'Sandwich', 'Alfajores', 'Eggs',
       'Brownie', 'Dulce de Leche', 'Honey', 'The BART', 'Granola',
       'Fairy Doors', 'Empanadas', 'Keeping It Local', 'Art Tray',
       'Bowl Nic Pitt', 'Bread Pudding', 'Adjustment', 'Truffles',
       'Chimichurri Oil', 'Bacon', 'Spread', 'Kids biscuit', 'Siblings',
       'Caramel bites', 'Jammie Dodgers', 'Tiffin', 'Olum & polenta',
       'Polenta', 'The Nomad', 'Hack the stack', 'Bakewell',
       'Lemon and coconut', 'Toast', 'Scone', 'Crepes', 'Vegan mincepie',
       'Bare Popcorn', 'Muesli', 'Crisps', 'Pintxos', 'Gingerbread syrup',
       'Panatone', 'Brioche and salami', 'Afternoon with the baker',
       'Salad', 'Chicken Stew', 'Spanish Brunch',
       'Raspberry shortbread sandwich', 'Extra Salami or Feta',
       'Duck egg', 'Baguette', "Valentine's card", 'Tshirt',
       'Vegan Feast', 'Postcard', 'Nomad bag', 'Chocolates',
       'Coffee granules ', 'Drinking chocolate spoons ',
       'Christmas common', 'Argentina Night', 'Half slice Monster ',
       'Gift voucher', 'Cherry me Dried fruit', 'Mortimer', 'Raw bars',
       'Tacos/Fajita'], dtype=object)

In [216]:
market['Item'].value_counts().count()

94

In [217]:
Basket =  market.groupby(['Transaction','Item'])['Transaction'].sum().unstack().reset_index().fillna(0).set_index('Transaction')

In [218]:
Basket.head(10)

Item,Adjustment,Afternoon with the baker,Alfajores,Argentina Night,Art Tray,Bacon,Baguette,Bakewell,Bare Popcorn,Basket,...,The BART,The Nomad,Tiffin,Toast,Truffles,Tshirt,Valentine's card,Vegan Feast,Vegan mincepie,Victorian Sponge
Transaction,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [219]:
Basket.shape

(9465, 94)

In [220]:
# Convert nilai menjadi 0 dan 1

def encode_units(x):
    if x <= 0:
        return 0
    if x >= 1:
        return 1

In [221]:
Basket.columns

Index(['Adjustment', 'Afternoon with the baker', 'Alfajores',
       'Argentina Night', 'Art Tray', 'Bacon', 'Baguette', 'Bakewell',
       'Bare Popcorn', 'Basket', 'Bowl Nic Pitt', 'Bread', 'Bread Pudding',
       'Brioche and salami', 'Brownie', 'Cake', 'Caramel bites',
       'Cherry me Dried fruit', 'Chicken Stew', 'Chicken sand',
       'Chimichurri Oil', 'Chocolates', 'Christmas common', 'Coffee',
       'Coffee granules ', 'Coke', 'Cookies', 'Crepes', 'Crisps',
       'Drinking chocolate spoons ', 'Duck egg', 'Dulce de Leche', 'Eggs',
       'Ella's Kitchen Pouches', 'Empanadas', 'Extra Salami or Feta',
       'Fairy Doors', 'Farm House', 'Focaccia', 'Frittata', 'Fudge',
       'Gift voucher', 'Gingerbread syrup', 'Granola', 'Hack the stack',
       'Half slice Monster ', 'Hearty & Seasonal', 'Honey', 'Hot chocolate',
       'Jam', 'Jammie Dodgers', 'Juice', 'Keeping It Local', 'Kids biscuit',
       'Lemon and coconut', 'Medialuna', 'Mighty Protein', 'Mineral water',
       'Mortimer', 'Muesli', 'Muffin', 'My-5 Fruit Shoot', 'Nomad bag',
       'Olum & polenta', 'Panatone', 'Pastry', 'Pick and Mix Bowls', 'Pintxos',
       'Polenta', 'Postcard', 'Raspberry shortbread sandwich', 'Raw bars',
       'Salad', 'Sandwich', 'Scandinavian', 'Scone', 'Siblings', 'Smoothies',
       'Soup', 'Spanish Brunch', 'Spread', 'Tacos/Fajita', 'Tartine', 'Tea',
       'The BART', 'The Nomad', 'Tiffin', 'Toast', 'Truffles', 'Tshirt',
       'Valentine's card', 'Vegan Feast', 'Vegan mincepie',
       'Victorian Sponge'],
      dtype='object', name='Item')

In [222]:
Basket_sets = Basket.applymap(encode_units)

In [223]:
Basket_sets.head()

Item,Adjustment,Afternoon with the baker,Alfajores,Argentina Night,Art Tray,Bacon,Baguette,Bakewell,Bare Popcorn,Basket,...,The BART,The Nomad,Tiffin,Toast,Truffles,Tshirt,Valentine's card,Vegan Feast,Vegan mincepie,Victorian Sponge
Transaction,,,,,,,,,,,,,,,,,,,,,
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [224]:
Basket_sets.shape

(9465, 94)

In [225]:
frequent_itemsets = apriori(Basket_sets, min_support=0.05, use_colnames=True)

In [226]:
frequent_itemsets.shape

(11, 2)

In [227]:
rules = association_rules(frequent_itemsets, metric='lift', min_threshold=0.003)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Bread),(Coffee),0.327205,0.478394,0.090016,0.275105,0.575059,-0.066517,0.719561
1,(Coffee),(Bread),0.478394,0.327205,0.090016,0.188163,0.575059,-0.066517,0.828731
2,(Cake),(Coffee),0.103856,0.478394,0.054728,0.526958,1.101515,0.005044,1.102664
3,(Coffee),(Cake),0.478394,0.103856,0.054728,0.114399,1.101515,0.005044,1.011905

In [228]:
rules.shape

(4, 9)

In [229]:
rules[ (rules['lift'] >= 0.05) &
       (rules['confidence'] >= 0.5) ]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
2,(Cake),(Coffee),0.103856,0.478394,0.054728,0.526958,1.101515,0.005044,1.102664

In [230]:
#melihat item cakes dan coffie yang terjual
cakes = Basket['Cake'].sum()
coffees = Basket['Coffee'].sum()
print(f'Total cakes sold: {cakes} and total coffee sold: {coffees}')

Total cakes sold: 5932362.0 and total coffee sold: 27084057.0